#!/bin/sh
set -ex

case "$1" in
    list)
        for appname in /media/apps/*.app; do
            NAME=$(basename "$appname")
            VERSION=1.2.3
            printf -- '%s\t%s\n' "$NAME" "$VERSION"
        done
        exit 0
        ;;
    install)
        exit 0
        ;;
    remove)
        exit 0
        ;;
    prepare)
        exit 0
        ;;
    update-list)
        # means update-list is unsupported by this plugin
        exit 1
        ;;
    finalize)
        exit 0
        ;;
    *)
        exit 0
        ;;
esac
